apiVersion: v1
kind: Pod
metadata:
  name: myapp0
  labels:
    app.kubernetes.io/name: myapp0
spec:
  containers:
  - name: myapp
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
