apiVersion: v1
kind: Pod
metadata:
  name: simple-app
  labels:
    name: simple-app
spec:
  containers:
  - name: simple-app
    image: simple-app
  resources:
    requests:
      memory: “4Gi”
      cpu: 2
    limits:
    - default:
        cpu: 500m
        memory: 1Gi
      defaultRequest:
        cpu: 500m
        memory: 1Gi
      max:
        cpu: 1
        memory: 1Gi
      min:
        cpu: 100m
        memory: 500Mi
      type: container